sonar.projectKey=claimsense-ai
sonar.projectName=Insurance Claim Pre-Assurance
sonar.projectVersion=1.0.0

sonar.sources=backend/app
sonar.tests=backend/tests
sonar.language=py

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.11

sonar.exclusions=\
  **/venv/**,\
  **/__pycache__/**,\
  **/alembic/**,\
  **/scripts/**,\
  **/*.pyc

sonar.test.inclusions=backend/tests/**/*.py
sonar.coverage.exclusions=backend/tests/**,backend/scripts/**
